spring.application.name=razorpay

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/razorpayDB
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

