spring.application.name=razorpay

# Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/razorpayDB
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
